Feature/2/tv75 add module keycloak create form login and auto create user
cunglam/keycloak-phone-provider pull request #2
Opened 2023-05-15 12:09 UTC by NguyenQuocVuong1999

2023-05-15 17:14 UTC, cunglam requested changes

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +    private UserModel getUser(AuthenticationFlowContext context, MultivaluedMap<String, String> inputData) {
Comment là copy từ đâu ra để sau này có cần mình sẽ xem lại

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        }
Nếu a ko nhầm thì từ đầu hàm tới đây là chú copy từ thằng Abstract ra, nếu vậy tách ra thành hàm riêng và đặt tên hàm, comment để mình hiểu là hàm này lấy từ chỗ khác

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +            user.setAttribute("phoneNumberVerified", Arrays.asList("true"));
cái biến này ko cần thiết đâu, ngoài ra chú cần tạo thêm 1 cái credential nữa để nó ko cần vào cái màn hình `Config MFA Authen`

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        if (user == null) {
phần này là phần tạo user thì cũng tách ra 1 hàm riêng

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        return user != null && validateUser(context, user, formData);
Tại sao ko đặt phần tạo user vào đây để nó tách biệt phần code mình thêm ra khỏi phần code copy từ keycloak sang nhỉ?

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        LoginFormsProvider forms = context.form();
code hàm này giống hệt cái username form thì sao ko gọi lại hàm từ nó?

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        return form.createLoginUsername();
cái này cũng thế?

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        if (context.getRealm().isLoginWithEmailAllowed())
Cái này cũng thế này, nhưng khả năng có chút khác ở message lỗi trả ra, có thể mình cần trả ra lỗi là invalid phone number

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/providers/spi/impl/DefaultPhoneProvider.java
> +        this.targetHourMaximum = config.getInt("targetHourMaximum", 60);
a nghĩ là để tầm 10 -20 là cùng thôi để tránh spam tin nhắn, còn khi test thì mình cấu hình là dc

2023-05-15 17:14 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
Mà có viết test dc cho mấy class này ko nhỉ?

2023-05-16 02:28 UTC, NguyenQuocVuong1999 commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        LoginFormsProvider forms = context.form();
![image](https://github.com/cunglam/keycloak-phone-provider/assets/35886548/d601c459-baed-46c4-8c9a-422aedfffaba)
tại nó đang là protected và em không được sửa nên không lấy được ạ

2023-05-16 03:09 UTC, NguyenQuocVuong1999 commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        }
không anh, em lấy từ PhoneUsernamePasswordForm, class này em có thể sửa, nên những hàm nào không sửa em sẽ lấy luôn từ class này, còn hàm nào cần sửa thì em sẽ comment lại nhé

2023-05-16 03:30 UTC, NguyenQuocVuong1999 commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        return form.createLoginUsername();
cái này cũng là hàm protected ạ

2023-05-17 17:13 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/Utils.java
> +        System.out.println("defaultRegion " + defaultRegion);
Bỏ log đi?

2023-05-18 02:13 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/Utils.java
> +    public static String defaultRegion(KeycloakSession session) {
Cái hàm này để làm gì ý nhỉ?

2023-05-18 02:17 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +    private UserModel createUserModel(MultivaluedMap<String, String> inputData, AuthenticationFlowContext context) {
Chuyển hàm này lên gần chỗ nó sử dụng cho dễ đọc

2023-05-18 02:18 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        username = standardizePhoneNumber(context.getSession(), username);
a nghĩ gộp dòng trên với dòng này lại để chỉ có 1 biến username thôi, tránh lỗi hoặc khó hiểu

2023-05-18 02:19 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +    private void createCredential(AuthenticationFlowContext context, String username, UserModel user) {
chuyển hàm này xuống chỗ dùng nó

2023-05-18 02:21 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        ocp.createCredential(context.getRealm(), user,
Cái hàm này nó tạo ra cái credential với giá trị như nào ý nhỉ, vì lúc chưa đăng nhập xong có thể 1 số giá trị nó chưa có

2023-05-18 02:22 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +    private String standardizePhoneNumber(KeycloakSession session, String phoneNumber) {
Cho hàm này sang util dc ko nhỉ, vì cái này là hàm dùng chung dc ở nhiều chỗ đấy

2023-05-18 02:23 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserForm.java
> +        LoginFormsProvider forms = context.form();
ok

2023-05-18 02:24 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/authentication/authenticators/browser/PhoneLoginAndAutoCreateUserFormFactory.java
> +    public static final String PROVIDER_ID = "auth-phone-form";
tên này chưa rõ nghĩa lắm nhỉ, xem lại tên khác mô tả rõ ràng hơn

2023-05-18 02:26 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/providers/spi/impl/DefaultPhoneProvider.java
> +        this.targetHourMaximum = config.getInt("targetHourMaximum", 20);
ko sửa ở đây nhé, cần thay đổi thì đổi ở cấu hình là dc rồi

2023-05-18 08:34 UTC, cunglam commented on keycloak-phone-provider/src/main/java/cc/coopersoft/keycloak/phone/providers/spi/impl/DefaultPhoneProvider.java
> +        user.setAttribute("latest-otp", Collections.singletonList(token.getCode()));
Cái này phải viết ở module gửi sms chứ, để ở đây là thay đổi code thật rồi

2023-05-18 08:44 UTC, merged